In [1]:
import pandas as pd
df=pd.read_csv("spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [5]:
df['spam']=df.Category.apply(lambda x:1 if x=='spam' else 0)
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [6]:
df.drop('Category',axis='columns',inplace=True)
df.head()

Message  spam
0  Go until jurong point, crazy.. Available only ...     0
1                      Ok lar... Joking wif u oni...     0
2  Free entry in 2 a wkly comp to win FA Cup fina...     1
3  U dun say so early hor... U c already then say...     0
4  Nah I don't think he goes to usf, he lives aro...     0

In [7]:
x=df.Message
y=df.spam

In [49]:
from sklearn.feature_extraction.text import CountVectorizer
v=CountVectorizer()
count=v.fit_transform(x)


In [11]:
count

<5572x8709 sparse matrix of type '<class 'numpy.int64'>'
	with 74098 stored elements in Compressed Sparse Row format>

In [17]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(count,y,test_size=0.1)

In [18]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(xtrain,ytrain)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [19]:
model.score(xtest,ytest)

0.9802867383512545

In [20]:
model.predict(xtest)

array([0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,

In [21]:
ytest

792     0
2528    0
3077    0
1993    1
1251    0
       ..
866     1
2664    1
311     0
540     0
1720    0
Name: spam, Length: 558, dtype: int64

In [46]:
emails=['Hey danny wanna go for a walk',
        'Upto 20% discount on under garments']

ecount=v.transform(emails)

In [47]:
model.predict(ecount)

array([0, 1], dtype=int64)

In [50]:
from sklearn.datasets import load_wine

In [51]:
wi=load_wine()

In [52]:
dir(wi)

['DESCR', 'data', 'feature_names', 'target', 'target_names']

In [56]:
wi.target_names

array(['class_0', 'class_1', 'class_2'], dtype='<U7')

In [58]:
df1=pd.DataFrame(wi.data,columns=wi.feature_names)
df1

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0      14.23        1.71  2.43               15.6      127.0           2.80   
1      13.20        1.78  2.14               11.2      100.0           2.65   
2      13.16        2.36  2.67               18.6      101.0           2.80   
3      14.37        1.95  2.50               16.8      113.0           3.85   
4      13.24        2.59  2.87               21.0      118.0           2.80   
..       ...         ...   ...                ...        ...            ...   
173    13.71        5.65  2.45               20.5       95.0           1.68   
174    13.40        3.91  2.48               23.0      102.0           1.80   
175    13.27        4.28  2.26               20.0      120.0           1.59   
176    13.17        2.59  2.37               20.0      120.0           1.65   
177    14.13        4.10  2.74               24.5       96.0           2.05   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     od280/od315_of_diluted_wines  proline  
0                            3.92   1065.0  
1                            3.40   1050.0  
2                            3.17   1185.0  
3                            3.45   1480.0  
4                            2.93    735.0  
..                            ...      ...  
173                          1.74    740.0  
174                          1.56    750.0  
175                          1.56    835.0  
176                          1.62    840.0  
177                          1.60    560.0  

[178 rows x 13 columns]

In [59]:
df1['target']=wi.target

In [62]:
df1

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0      14.23        1.71  2.43               15.6      127.0           2.80   
1      13.20        1.78  2.14               11.2      100.0           2.65   
2      13.16        2.36  2.67               18.6      101.0           2.80   
3      14.37        1.95  2.50               16.8      113.0           3.85   
4      13.24        2.59  2.87               21.0      118.0           2.80   
..       ...         ...   ...                ...        ...            ...   
173    13.71        5.65  2.45               20.5       95.0           1.68   
174    13.40        3.91  2.48               23.0      102.0           1.80   
175    13.27        4.28  2.26               20.0      120.0           1.59   
176    13.17        2.59  2.37               20.0      120.0           1.65   
177    14.13        4.10  2.74               24.5       96.0           2.05   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     od280/od315_of_diluted_wines  proline  target  
0                            3.92   1065.0       0  
1                            3.40   1050.0       0  
2                            3.17   1185.0       0  
3                            3.45   1480.0       0  
4                            2.93    735.0       0  
..                            ...      ...     ...  
173                          1.74    740.0       2  
174                          1.56    750.0       2  
175                          1.56    835.0       2  
176                          1.62    840.0       2  
177                          1.60    560.0       2  

[178 rows x 14 columns]

In [63]:
x=df1.drop('target',axis='columns')

In [64]:
y=df1.target

In [66]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.1)

In [67]:
xtrain

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
100    12.08        2.08  1.70               17.5       97.0           2.23   
140    12.93        2.81  2.70               21.0       96.0           1.54   
51     13.83        1.65  2.60               17.2       94.0           2.45   
104    12.51        1.73  1.98               20.5       85.0           2.20   
165    13.73        4.36  2.26               22.5       88.0           1.28   
..       ...         ...   ...                ...        ...            ...   
24     13.50        1.81  2.61               20.0       96.0           2.53   
150    13.50        3.12  2.62               24.0      123.0           1.40   
156    13.84        4.12  2.38               19.5       89.0           1.80   
60     12.33        1.10  2.28               16.0      101.0           2.05   
134    12.51        1.24  2.25               17.5       85.0           2.00   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
100        2.17                  0.26             1.40             3.30  1.27   
140        0.50                  0.53             0.75             4.60  0.77   
51         2.99                  0.22             2.29             5.60  1.24   
104        1.92                  0.32             1.48             2.94  1.04   
165        0.47                  0.52             1.15             6.62  0.78   
..          ...                   ...              ...              ...   ...   
24         2.61                  0.28             1.66             3.52  1.12   
150        1.57                  0.22             1.25             8.60  0.59   
156        0.83                  0.48             1.56             9.01  0.57   
60         1.09                  0.63             0.41             3.27  1.25   
134        0.58                  0.60             1.25             5.45  0.75   

     od280/od315_of_diluted_wines  proline  
100                          2.96    710.0  
140                          2.31    600.0  
51                           3.37   1265.0  
104                          3.57    672.0  
165                          1.75    520.0  
..                            ...      ...  
24                           3.82    845.0  
150                          1.30    500.0  
156                          1.64    480.0  
60                           1.67    680.0  
134                          1.51    650.0  

[160 rows x 13 columns]

In [68]:
ytrain

100    1
140    2
51     0
104    1
165    2
      ..
24     0
150    2
156    2
60     1
134    2
Name: target, Length: 160, dtype: int32

In [72]:
from sklearn.naive_bayes import GaussianNB
model1=GaussianNB()
model1.fit(xtrain,ytrain)
model1.score(xtest,ytest)

1.0

In [70]:
from sklearn.naive_bayes import MultinomialNB
model2=MultinomialNB()
model2.fit(xtrain,ytrain)
model2.score(xtest,ytest)

0.8333333333333334

In [74]:
model1.predict(xtest)

array([1, 2, 0, 0, 0, 0, 1, 0, 1, 2, 1, 1, 0, 1, 2, 1, 0, 0])

In [75]:
ytest

66     1
133    2
7      0
23     0
9      0
10     0
64     1
46     0
127    1
130    2
87     1
62     1
17     0
125    1
141    2
89     1
31     0
26     0
Name: target, dtype: int32

In [76]:
model2.predict(xtest)

array([1, 2, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 2, 0, 0])

In [77]:
ytest

66     1
133    2
7      0
23     0
9      0
10     0
64     1
46     0
127    1
130    2
87     1
62     1
17     0
125    1
141    2
89     1
31     0
26     0
Name: target, dtype: int32